org: rperryng
app: telegram-wordle-bot
service: telegram-wordle-bot

frameworkVersion: '2'

custom:
  submissionsTable: 'submissions-table-${self:provider.stage}'
  groupsTable: 'groups-table-${self:provider.stage}'

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ca-central-1
  lambdaHashingVersion: '20201221'
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ SubmissionsTable, Arn ]
  environment:
    AWS_SUBMISSIONS_TABLE: ${self:custom.submissionsTable}
    AWS_GROUPS_TABLE: ${self:custom.groupsTable}

functions:
  api:
    handler: dist/app.handler
    environment:
      TELEGRAM_BOT_KEY: ${ssm:/telegram_bot_key, env:TELEGRAM_BOT_KEY}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    SubmissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.submissionsTable}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: N
          - AttributeName: wordleNumber
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: wordleNumber
            KeyType: RANGE

    GroupsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.groupsTable}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: N
          - AttributeName: userId
            AttributeType: N
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: groupId
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
