#!/usr/bin/env bash
set -eo pipefail
 
echo "Setting Webhook URL: ${TELEGRAM_WEBHOOK_URL}"
curl \
  --request POST \
  --url "https://api.telegram.org/bot${TELEGRAM_BOT_KEY}/setWebhook" \
  --header 'content-type: application/json' \
  --data "{\"url\": \"${TELEGRAM_WEBHOOK_URL}\"}"
