#!/usr/bin/env bash
set -eo pipefail
 
curl \
  --request POST \
  --verbose \
  --url "https://api.telegram.org/bot${TELEGRAM_API_KEY}/setWebhook" \
  --header 'content-type: application/json' \
  --data "{\"url\": \"${WEBHOOK_URL}\"}"
