#!/usr/bin/env bash
set -eo pipefail

SCRIPT_DIR="$(dirname "$0")"

function getNgrokUrl() {
  local result
  curl --fail --silent http://127.0.0.1:4040/api/tunnels > /dev/null

  if [ $? -ne 0 ]; then
    ngrok http 3000 > /dev/null &
  fi

  curl --silent http://127.0.0.1:4040/api/tunnels \
    | jq -r '.tunnels | .[] | select(.proto == "https") | .public_url'
}

rm -rf "${SCRIPT_DIR}/../dist"
yarn build:local
WEBHOOK_URL="$(getNgrokUrl)/dev"
source "${SCRIPT_DIR}/telegram-set-webhook-url"

yarn sls offline
